---
title: '5291'
output: pdf_document
date: "2023-04-24"
---

```{r}
library(tidyverse)
library(lubridate)
library(ggplot2)
library(reshape2)
library(zoo)
library(corrplot)
library(psych)
library(corrplot)
data<-read.csv("Desktop/air_pollution.csv")
head(data)
numeric_columns <- sapply(data, is.numeric)#numeric columns
numeric_columns
data$date <- ymd(data$date) # ymd() function 
```


```{r}
#check na
na_counts <- colSums(is.na(data))
print(na_counts)
summary(data)
```


```{r}
#1.line plots
plot(data$date, data$pollution_today, type = "l", xlab = "date", ylab = "Pollution")

data_l <- melt(data, id.vars = "date", variable.name = "Column", value.name = "Value")
ggplot(data_l, aes(x = date, y = Value, group = Column, color = Column)) +
  geom_line() +
  facet_wrap(~ Column, ncol = 1, scales = "free_y") +
  theme_minimal() +
  labs(title = "Time Series Data", x = "date", y = "Value")

```

```{r}
#2. compute the correlation matrix
cor_matrix <- cor(data[, -1])

# plot the correlation matrix

corrplot(cor_matrix, method = 'circle', type = 'upper', order = 'hclust', tl.col = 'black', tl.srt = 45, addCoef.col = 'black')

```
```{r}
#3.boxplot
data$Month <- format(data$date, "%m")
data$Year <- format(data$date, "%Y")
library(ggplot2)

# For months
ggplot(data, aes(x = as.factor(Month), y = pollution_today)) +
  geom_boxplot() +
  theme_minimal() +
  labs(title = "Box Plot by Month", x = "Month", y = "Pollution Today")

# For years
ggplot(data, aes(x = as.factor(Year), y = pollution_today)) +
  geom_boxplot() +
  theme_minimal() +
  labs(title = "Box Plot by Year", x = "Year", y = "Pollution Today")
```
```{r}
#4.seasonal plots
data$Day <- format(data$date, "%d")
ggplot(data, aes(x = as.numeric(Day), y = pollution_today, group = Year, color = Year)) +
  geom_line() +
  theme_minimal() +
  labs(title = "Seasonal Plot by Month", x = "Day", y = "Pollution Today") +
  facet_wrap(~Month, ncol = 4)  # Adjust the number of columns in the facet_wrap function as desired

ggplot(data, aes(x = as.numeric(Day), y = wnd_spd, group = Year, color = Year)) +
  geom_line() +
  theme_minimal() +
  labs(title = "Seasonal Plot by Month", x = "Day", y = "wnd_spd") +
  facet_wrap(~Month, ncol = 4)  # Adjust the number of columns in the facet_wrap function as desired

ggplot(data, aes(x = as.numeric(Day), y = snow, group = Year, color = Year)) +
  geom_line() +
  theme_minimal() +
  labs(title = "Seasonal Plot by Month", x = "Day", y = "snow") +
  facet_wrap(~Month, ncol = 4)  # Adjust the number of columns in the facet_wrap function as desired


ggplot(data, aes(x = as.numeric(Day), y = rain, group = Year, color = Year)) +
  geom_line() +
  theme_minimal() +
  labs(title = "Seasonal Plot by Month", x = "Day", y = "rain") +
  facet_wrap(~Month, ncol = 4)  # Adjust the number of columns in the facet_wrap function as desired

ggplot(data, aes(x = as.numeric(Day), y = wnd_spd, group = Year, color = Year)) +
  geom_line() +
  theme_minimal() +
  labs(title = "Seasonal Plot by Month", x = "Day", y = "wnd_spd") +
  facet_wrap(~Month, ncol = 4)  # Adjust the number of columns in the facet_wrap function as desired
```


```{r}
#5.Heatmaps

ggplot(data, aes(x = as.numeric(Month), y = as.numeric(Day), fill = dew)) +
  geom_tile() +
  theme_minimal() +
  scale_fill_gradientn(colors = c("grey", "yellow", "red"), name = "dew") +
  labs(title = "Heatmap of dew", x = "Month", y = "Day") +
  facet_wrap(~Year, ncol = 1)  # Adjust the number of columns in the facet_wrap function as desired

ggplot(data, aes(x = as.numeric(Month), y = as.numeric(Day), fill = rain)) +
  geom_tile() +
  theme_minimal() +
  scale_fill_gradientn(colors = c("grey", "yellow", "red"), name = "rain") +
  labs(title = "Heatmap of Pollution Today", x = "Month", y = "Day") +
  facet_wrap(~Year, ncol = 1)  # Adjust the number of columns in the facet_wrap function as desired
```